# Generated by Django 4.0.6 on 2022-11-10 20:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import email.policy


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('image', models.ImageField(null=True, upload_to='Posts')),
                ('content', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='signin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=50, verbose_name=email.policy.EmailPolicy)),
                ('password', models.CharField(max_length=10)),
                ('confirmpassword', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('Written_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date published')),
                ('image', models.ImageField(null=True, upload_to='Posts')),
                ('content', models.TextField(max_length=120)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
